// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQo-gee1--3hyTarfXSJ1rX5jREx7Jids',
    appId: '1:831881348142:web:e2802b7a144940312fcbbf',
    messagingSenderId: '831881348142',
    projectId: 'cirqle-d3015',
    authDomain: 'cirqle-d3015.firebaseapp.com',
    storageBucket: 'cirqle-d3015.appspot.com',
    measurementId: 'G-4E5T5ZNZDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgN6vDJhL3qfI4Q8P1FSyKiOUD9Q2O0j8',
    appId: '1:831881348142:android:06aae2b5eb483de92fcbbf',
    messagingSenderId: '831881348142',
    projectId: 'cirqle-d3015',
    storageBucket: 'cirqle-d3015.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzQXLCMcxDFJMVWLtjx1MB5SbQsNEFsKM',
    appId: '1:831881348142:ios:59904fb70c34fcb62fcbbf',
    messagingSenderId: '831881348142',
    projectId: 'cirqle-d3015',
    storageBucket: 'cirqle-d3015.appspot.com',
    iosBundleId: 'com.example.cirqle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzQXLCMcxDFJMVWLtjx1MB5SbQsNEFsKM',
    appId: '1:831881348142:ios:59904fb70c34fcb62fcbbf',
    messagingSenderId: '831881348142',
    projectId: 'cirqle-d3015',
    storageBucket: 'cirqle-d3015.appspot.com',
    iosBundleId: 'com.example.cirqle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQo-gee1--3hyTarfXSJ1rX5jREx7Jids',
    appId: '1:831881348142:web:0e6b8ec0c06865932fcbbf',
    messagingSenderId: '831881348142',
    projectId: 'cirqle-d3015',
    authDomain: 'cirqle-d3015.firebaseapp.com',
    storageBucket: 'cirqle-d3015.appspot.com',
    measurementId: 'G-1V1C2BMXNQ',
  );
}
